In [5]:
import numpy as np
import pandas as pd

#### Agregando Librerias

In [7]:
lista = list(range(1,11))
lista       #PARA IMPRIMIR SE PUEDE LLAMAR A LA VARIABLE DIRECTAMENTE

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Transformando la lista en Array

In [3]:
arreglo = np.array(lista) #np LLAMA A LA FUNCION QUE QUEREMOS UTILIZAR
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Corroborando el tipo de objeto

In [8]:
arreglo = np.array(lista)
type(arreglo)

numpy.ndarray

#### Corroborando el tipo de datos del arreglo

In [6]:
arreglo.dtype

dtype('int32')

#### Definiendo el Array de Int32 a Float32

In [9]:
np.array(arreglo, dtype=np.float32)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

In [10]:
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arreglo.astype(np.float32)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

#### (arriba) Sacar promedio


In [12]:
promedio = np.mean(arreglo)
promedio

5.0

In [13]:
mediana = np.median(arreglo)
mediana

5.0

#### (abajo) Sacar Desviacion Estandar

In [9]:
desviacion = np.std(arreglo)
desviacion

2.8722813232690143

#### Utilizando RANDOM

In [10]:
arreglo_aleatorio = np.random.rand(5)   #DENTRO DE PARENTESIS ME INDICA CUANTOS NUM SACARE
arreglo_aleatorio       #EN ESTE CASO SOLO SACARA NUMEROS DECIMALES

array([0.94678621, 0.85623136, 0.35316409, 0.7074959 , 0.85024653])

#### Arreglo Aleatorio con Enteros

In [11]:
arreglo_aleatorio2 = np.random.randint(1,5,10)  #DE ESTE NUMERO; HASTA ESTE NUMERO; CANTIDAD DE VECES
arreglo_aleatorio2

array([1, 3, 4, 1, 2, 2, 1, 2, 2, 1])

#### Creando una Matriz 3x3 Aleatoria

In [14]:
matriz = np.random.rand(3,3)
matriz

array([[0.32472706, 0.66465435, 0.07472462],
       [0.40477936, 0.12499178, 0.29492035],
       [0.77104774, 0.6187817 , 0.90078421]])

#### Generando una Matriz de 10 Numeros Enteros del 1 al 100

In [19]:
matriz2 = np.random.randint(1, 101, (10, 10))   #AL FINAL; DIGO QUE TENGA 10 ELEMENTOS HORIZONTAL, Y != ELEMENTOS VERTICAL
matriz2

array([[ 79,  13,  97,  64,  15,  67,  51,  82,  34,   2],
       [ 74,  30,  18,  58,  14,  83,  97,  83,  30,   8],
       [ 41,   9,  15,  59,  88,  79,   3,  32,  68,  93],
       [100,  51,  68,  38,  77,   5,  68,  40,  74,  85],
       [ 85,  33,  11,   3,  39,  35,  66,  19,  81,  26],
       [ 99,  82,  91,  29,  95,  99,  21,  15,  44,  22],
       [ 61,  16,   1,  28,  38,  37,  93,  59,  91,  62],
       [ 86,   7,  37,  46,   4,  54,  23,  74,  65,  75],
       [ 70,  78,  92,  37,  70,  98,  47,  77,  80,  99],
       [ 43,  61,  74,  17,  45,  40,  47,  33,  81,  44]])

#### Trabajar con PANDAS